### ISSUE TITLE
Splash screen improvements for WordPress.com onboarding experience

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack-start#57]
The 'legacy' version of Jetpack Onboarding has a first screen that asks customers if they'd like help setting up their site. Since the new version requires them to leave wp-admin and visit WordPress.com to get set up, we should make it more clear what's about to happen on that first screen. We should also take a look at the visual elements and branding to make sure it matches the WordPress.com onboarding experience and is maximally friendly. An illustration would help. 

@joanrho and I will take a crack at the design of this splash and update this ticket when we're ready.

**Comment by tyxla** [comment]
Can you folks open an issue in the WP Calypso repo and have it in the JPO project board (https://github.com/Automattic/wp-calypso/projects/55)? Thanks!

**Comment by rickybanister** [comment]
This issue was opened in error. We do not need a splash screen in the plugin. The plugin will no longer be required for the new WordPress.com-centric flow.
